### ISSUE TITLE
Require either `streamlit` OR `streamlit-nightly` to avoid conflicts

### ISSUE THREAD

**Issue by arturadib** [okld/streamlit-ace#10]
If I install `streamlit-ace` with `streamlit-nightly` already installed, it'll install `streamlit` which causes issues with the nightly version:

```
$ pip list | grep streamlit
streamlit-nightly             0.70.1.dev20201101

$ pip install streamlit-ace

$ pip list | grep streamlit
streamlit                     0.71.0
streamlit-ace                 0.0.4
streamlit-nightly             0.70.1.dev20201101
```

**Comment by okld** [comment]
Hello @arturadib, I've indeed encountered that issue myself, but I'm not sure how to conditionnally ignore to install `streamlit` if `streamlit-nightly` is already installed. [Environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) or [extras_require](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies) doesn't seem to help here.

And this issue would be common to every other streamlit components.
