### ISSUE TITLE
Customise width and height 

### ISSUE THREAD

**Issue by iamashwin99** [okld/streamlit-ace#12]
Is there any way to change the width and height of the ace editor widget?

**Comment by okld** [comment]
Hello @iamashwin99, you can only customize the height like so: `st_ace(height=380)`

Why would you customize the width?
If you want to display Ace side-by-side with some other content, you can rely on streamlit's columns.
Here's an app showcasing this layout: https://share.streamlit.io/akrolsmir/streamlit-snippet/main

**Comment by iamashwin99** [comment]
@okld thank you for your tip on using streamlit's columns.
It solved my problem!

**Comment by Tisha-linkenite** [comment]
I want to customize the width of the editor, the column thing doesn't seem to work.
