### ISSUE TITLE
trouble loading the streamlit_ace.ace component

### ISSUE THREAD

**Issue by iamashwin99** [okld/streamlit-ace#13]
I have a strange problem that occurs randomly.
I have deployed a streamlit app that uses streamlit_ace editor. When I visit the web page, I get the following error
 sometimes and other times it works fine! 
```
Your app is having trouble loading the streamlit_ace.ace component.

(The app is attempting to load the component from **, and hasn't received its "streamlit:componentReady"** message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?

```

![Screenshot_20201223_165600](https://user-images.githubusercontent.com/46030335/102991835-0770f980-4540-11eb-814d-5945030420e4.png)
I have it deployed [here](https://back-plt.herokuapp.com/) and [here](https://share.streamlit.io/iamashwin99/back-plt/main/main.py)
It works consistently when run from my laptop with the exact same dependency and versions installed.
here's the output when the app is run locally. 
![Screenshot_20201223_165910](https://user-images.githubusercontent.com/46030335/102991909-32f3e400-4540-11eb-9a72-15797f18512d.png)

I don't think this is an issue with streamlit-ace, however, I am hoping someone here might recognise the issue and guide me.
If it helps, the source is hosted [here](https://github.com/iamashwin99/back-plt/blob/main/main.py)

**Comment by okld** [comment]
Hello @iamashwin99,

Hmm, weird indeed. Maybe Ace takes time to load, and Streamlit timeout is too short.
Gonna have a deeper look a little bit later, as this may affect other components too.

I just checked a few times now, I couldn't reproduce the issue though.

**Comment by iamashwin99** [comment]
> I just checked a few times now, I couldn't reproduce the issue though.

did you try it out here https://back-plt.herokuapp.com/ or https://share.streamlit.io/iamashwin99/back-plt/main/main.py ?

If they are working as expected, could you try throttling network and try again?

**Comment by erumoico** [comment]
I tried your URLs and I gave the same problem at both of them. I upgrade streamlit on my machine to version `streamlit-0.75.0` and now I have the same problem with my app. So I also interest what is the problem.

Before the upgrade (from version `streamlit-0.74.1`), it sometimes happened that the component did not fully load. In this case, only component's `public/index.html` was loaded without anything in `<div id="root"></div>` tag. But maybe it is a different issue.

> Hmm, weird indeed. Maybe Ace takes time to load, and Streamlit timeout is too short.

How can I increase the timeout?

**Comment by iamashwin99** [comment]
@erumoico  are you using st.columns somewhere in your app?
I started getting these issues when I used them and when I removed the columns and just pushed the content one below the other the error seems to go away, I still, however, don't think that's the cause.

**Comment by erumoico** [comment]
At first I should tell, that I sped up my component and now yellow warning box about troubles with loading disappear. (I sped up it simply with move files of streamlit and my component to faster medium.)

Now I only have a trouble with empty `<div id="root"></div>` tag in my component, so maybe I should post my issue on the streamlit issue tracking.

Now, to your hint. Yes, I have my component inside a column of st.beta_columns(). So, I tried it, but `<div id="root"></div>` tag of my component is still empty sometimes. But I thank you for your effort.

**Comment by erumoico** [comment]
I have found the timeout at [`streamlit/frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx:52`](https://github.com/streamlit/streamlit/blob/b4a9f3e2c9f9a56bbc2842fd43150fe4b0bdfcab/frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx#L52):
```
export const COMPONENT_READY_WARNING_TIME_MS = 3000
```
Unfortunately, I haven't found how to set it up yet without interfering with the streamlite code.

**Comment by amrrs** [comment]
strangely, removing `st.beta_columns` from my code fixed the same issue (after reading this thread) so thanks @iamashwin99 @erumoico 🎉

**Comment by okld** [comment]
As highlighted by @erumoico, a solution would be to change components' timeout in streamlit. Thank you for opening the issue on their side (streamlit/streamlit#2888).

**Comment by okld** [comment]
This pull request should fix the issue: https://github.com/streamlit/streamlit/pull/3315.
The component will still be able to load even if the `COMPONENT_READY` timeout is reached.

**Comment by amrrs** [comment]
Thanks @okld

**Comment by ThermodynamicBeta** [comment]
I am getting this issue now, even in the lastest streamlit version. It works locally, but when deployed to the cloud I get the yellow box warning.
