### ISSUE TITLE
Can't input code properly into st.ace editor.

### ISSUE THREAD

**Issue by Spiruel** [okld/streamlit-ace#29]
I am having the same issue as described here: https://stackoverflow.com/questions/8021821/arrow-keys-and-delete-work-in-ace-editor-but-typing-text-doesnt-work

I cannot type code into the editor even when it's set to editable. Only arrow keys and delete work.

You can see the bug in action on the 'Ice' page here: https://share.streamlit.io/spiruel/satschool/main/app.py

Is there a way to overcome this in streamlit?

Thanks

**Comment by okld** [comment]
Hello @Spiruel,

Actually this is because you configured Ace to use VIM keybindings. You just have to get rid of [this parameter](https://github.com/Spiruel/SatSchool/blob/main/apps/ice.py#L100) in your code to make it work as you expect.
