### ISSUE TITLE
Add MaxLines:Infinite Option

### ISSUE THREAD

**Issue by theimposingdwarf** [okld/streamlit-ace#4]
One of my use cases involves a desire to have the ace editor automatically resize. The Ace Editor React Component appears to have this capability built in but requires setting the "max_lines" property to javascript Infinite. If we could assign the max_lines property infinity with either float('inf') or the string "Infinity" this would enable the auto resize functionality. 

Alternatively, the default could be sent to Infinite so that the editor resizes by default but becomes fixed when the max_lines property is manually assigned.

**Comment by okld** [comment]
Hello @theimposingdwarf, sorry for this very late reply!
Making this possible will require some additional work due to some iframe auto resizing issues, but it can be done anyway. I'll work on it when I have time. Stay tuned!

**Comment by theimposingdwarf** [comment]
Awesome, thank you!
