### ISSUE TITLE
Apply code changes without CTRL + Enter

### ISSUE THREAD

**Issue by kellyamanda** [okld/streamlit-ace#6]
Was just using an app on mobile that uses this editor and the problem on mobile is that I can't do CTRL + Enter to make changes, because that's not a keyboard option on mobile! Would be great to have another way to do this - a button option for example.

**Comment by okld** [comment]
Hello @kellyamanda,
Thanks for opening this issue!

You're right, I think I'll add a button by default when auto update is set to false. Working on it really soon!
